version: '3.2'

services:
  maridb:
    image: lsioarmhf/mariadb
    volumes: 
      - type: bind
        name: config
        source: /srv/dev-disk-by-id-ata-TOSHIBA_MQ01ABD100_9537SNBIS-part2/mariadb
        target: /config
    environment:
      TZ: Africa/Johannesburg
      MYSQL_ROOT_PASSWORD: 'Ug0j!neu'
    ports:
      - 3306:3306
volumes:
  config:
